# Generated by Django 5.0.4 on 2024-05-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selfdefenceclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('place', models.CharField(default='', max_length=50)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('class_type', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
