# Generated by Django 5.0.4 on 2024-05-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talentgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('members', models.CharField(default='', max_length=50)),
                ('description', models.FileField(default='', max_length=50, upload_to='')),
            ],
        ),
    ]
