# Generated by Django 5.0.4 on 2024-05-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentgroup',
            name='members',
        ),
    ]
