# Generated by Django 5.0.4 on 2024-05-30 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_remove_inbox_datetime_remove_inbox_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='gpid',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='userid',
        ),
        migrations.AddField(
            model_name='inbox',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inbox',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, null=True)),
                ('gpid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgWEWRE_id', to='Admin_App.talentgroup')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_WDEWQperson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
