# Generated by Django 5.0.4 on 2024-05-30 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_remove_inbox_gpid_remove_inbox_userid_inbox_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='gpid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgWEWRE_id', to='Admin_App.talentgroup'),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_WDEWQperson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='group',
        ),
    ]
