# Generated by Django 5.0.4 on 2024-05-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_members_gpid_alter_members_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='classvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='')),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ertewrtwert', to='Admin_App.classes')),
            ],
        ),
    ]
