# Generated by Django 5.0.4 on 2024-05-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0009_classvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gftftyfftyfuoiop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adssigfetwrtewrthjkghjd', to='Admin_App.classes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdassigfhjkadgtsdgghjd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
