# Generated by Django 5.0.4 on 2024-06-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0012_groupinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinbox',
            name='groupid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdererr', to='Admin_App.talentgroup'),
        ),
    ]
