# Generated by Django 5.0.4 on 2024-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0013_groupinbox_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentgroup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
