# Generated by Django 5.0.4 on 2024-05-28 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHO', '0003_delete_healthawarness_alter_schemas_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemas',
            old_name='titile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osfsdiop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemas',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osdfsdiop', to=settings.AUTH_USER_MODEL),
        ),
    ]
