# Generated by Django 5.0.4 on 2024-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHO', '0004_rename_titile_schemas_title_healthcheckup_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
