# Generated by Django 5.0.2 on 2024-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHO', '0005_alter_healthcheckup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
