# Generated by Django 5.0.4 on 2024-05-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courses_userid_hostals_userid_jobs_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostals',
            name='Rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostals',
            name='Tenant_preferred',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hostals',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostals',
            name='facilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hostals',
            name='rule',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
