# Generated by Django 5.0.4 on 2024-05-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courses_duration_hostals_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
