# Generated by Django 5.0.4 on 2024-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_courses_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courceimage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hostals',
            name='hostalimage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='firmimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
