# Generated by Django 5.0.4 on 2024-06-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courses_courceimage_hostals_hostalimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
