# Generated by Django 5.0.4 on 2024-06-14 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_jobs_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('cource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oirewop', to='organization.courses')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oireterwtwop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
