# Generated by Django 5.0.4 on 2024-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
