# Generated by Django 5.0.4 on 2024-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_enroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
