# Generated by Django 5.0.4 on 2024-06-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
