# Generated by Django 5.0.4 on 2024-06-15 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='hostalfeedback',
        ),
    ]
