# Generated by Django 5.0.4 on 2024-06-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_courseexams_coursevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseexams',
            old_name='hostal_name',
            new_name='link',
        ),
    ]
