# Generated by Django 5.0.4 on 2024-06-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_rename_hostal_name_courseexams_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexams',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yyrrr', to='organization.courses'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdfff', to='organization.courses'),
        ),
    ]
