# Generated by Django 5.0.4 on 2024-06-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_courseexams_courseid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseexams',
        ),
    ]
