# Generated by Django 5.0.4 on 2024-06-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_courseexams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseexams',
        ),
    ]
