# Generated by Django 5.0.4 on 2024-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_courseexams'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexams',
            name='linkdf',
            field=models.CharField(default='', max_length=250),
        ),
    ]
