# Generated by Django 5.0.4 on 2024-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_courseexams_linkdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexams',
            name='linkdf',
        ),
        migrations.AddField(
            model_name='courseexams',
            name='current_time',
            field=models.TimeField(null=True),
        ),
    ]
