# Generated by Django 5.0.4 on 2024-06-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_remove_courseexams_linkdf_courseexams_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexams',
            name='current_time',
        ),
    ]
