# Generated by Django 5.0.4 on 2024-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_courseexams_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexams',
            name='current_time',
            field=models.DateTimeField(null=True),
        ),
    ]
