# Generated by Django 4.2.4 on 2024-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHORegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DHOname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(default='', max_length=50)),
                ('yearofexperience', models.CharField(default='', max_length=50)),
                ('contact', models.IntegerField(null=True)),
                ('district', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('id_proof', models.FileField(null=True, upload_to='id_proof/')),
            ],
        ),
        migrations.CreateModel(
            name='orgRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.FileField(default='', max_length=50, upload_to='')),
                ('description', models.CharField(default='', max_length=50)),
                ('id_proof', models.FileField(null=True, upload_to='id_proof/')),
            ],
        ),
        migrations.CreateModel(
            name='policeofficerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officername', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('rank', models.CharField(default='', max_length=50)),
                ('contact', models.IntegerField(null=True)),
                ('district', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('id_proof', models.FileField(null=True, upload_to='id_proof/')),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='address',
            new_name='houseno',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='gender',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='register',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='register',
            name='license',
        ),
        migrations.RemoveField(
            model_name='register',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.FileField(default='', max_length=50, upload_to=''),
        ),
    ]
