# Generated by Django 4.2.4 on 2024-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_orgregister_contact_register_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
