# Generated by Django 5.0.4 on 2024-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_register_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DHORegister',
        ),
        migrations.DeleteModel(
            name='orgRegister',
        ),
        migrations.DeleteModel(
            name='policeofficerRegister',
        ),
        migrations.AddField(
            model_name='register',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='id_proof',
            field=models.FileField(null=True, upload_to='id_proof/'),
        ),
        migrations.AddField(
            model_name='register',
            name='qualification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='rank',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='yearofexperience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='usertype',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
