# Generated by Django 5.0.4 on 2024-05-11 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_dhoregister_delete_orgregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='district',
            field=models.CharField(choices=[('', 'Select'), ('Thrissur', 'Thrissur')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(choices=[('', 'Select'), ('Kerala', 'Kerala')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsage', models.FileField(default='', max_length=50, upload_to='')),
                ('recieverid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rid', to=settings.AUTH_USER_MODEL)),
                ('senderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
