# Generated by Django 5.0.4 on 2024-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_register_district_alter_register_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
