# Generated by Django 5.0.4 on 2024-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_register_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
