# Generated by Django 5.0.2 on 2024-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
